/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  opend2c                                        */
/*      FILE         :  opend2c.c                                      */
/*      DESCRIPTION  :  Main Program                                   */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  RX62N                                          */
/*  													               */
/*      This file is generated by KPIT Eclipse.                        */
/*  													               */
/***********************************************************************/                                                                          
																							
#define __RX_LITTLE_ENDIAN__ 1
#include "iodefine.h"



int main(void)
{
    // TODO: add application code here

    while (1) {

    }
  return 0;
}
